--------------------------------------------------------
--  DDL for Table C_POSITION
--------------------------------------------------------

  CREATE TABLE "TOM"."C_POSITION" 
   (	"CP_CODE" NUMBER, 
	"CP_NAME" NVARCHAR2(10)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "TOM"."C_POSITION"."CP_CODE" IS '코칭포지션코드';
   COMMENT ON COLUMN "TOM"."C_POSITION"."CP_NAME" IS '코칭포지션명';
   COMMENT ON TABLE "TOM"."C_POSITION"  IS '코칭포지션';
