--------------------------------------------------------
--  Constraints for Table COACHING_STAFF
--------------------------------------------------------

  ALTER TABLE "TOM"."COACHING_STAFF" MODIFY ("CS_CODE" NOT NULL ENABLE);
  ALTER TABLE "TOM"."COACHING_STAFF" MODIFY ("T_CODE" NOT NULL ENABLE);
  ALTER TABLE "TOM"."COACHING_STAFF" MODIFY ("CD_CODE" NOT NULL ENABLE);
  ALTER TABLE "TOM"."COACHING_STAFF" MODIFY ("CP_CODE" NOT NULL ENABLE);
  ALTER TABLE "TOM"."COACHING_STAFF" MODIFY ("CS_NAME" NOT NULL ENABLE);
  ALTER TABLE "TOM"."COACHING_STAFF" MODIFY ("CS_BIRTH" NOT NULL ENABLE);
  ALTER TABLE "TOM"."COACHING_STAFF" MODIFY ("CS_BN" NOT NULL ENABLE);
  ALTER TABLE "TOM"."COACHING_STAFF" MODIFY ("CS_HEIGHT" NOT NULL ENABLE);
  ALTER TABLE "TOM"."COACHING_STAFF" MODIFY ("CS_WEIGHT" NOT NULL ENABLE);
  ALTER TABLE "TOM"."COACHING_STAFF" MODIFY ("CS_JY" NOT NULL ENABLE);
  ALTER TABLE "TOM"."COACHING_STAFF" ADD CONSTRAINT "PK_COACHING_STAFF" PRIMARY KEY ("CS_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
