--------------------------------------------------------
--  DDL for Table COACHING_STAFF
--------------------------------------------------------

  CREATE TABLE "TOM"."COACHING_STAFF" 
   (	"CS_CODE" NUMBER, 
	"T_CODE" NUMBER, 
	"CD_CODE" NUMBER, 
	"CP_CODE" NUMBER, 
	"CS_NAME" NVARCHAR2(20), 
	"CS_BIRTH" DATE, 
	"CS_BN" NUMBER, 
	"CS_HEIGHT" NUMBER, 
	"CS_WEIGHT" NUMBER, 
	"CS_ES" NVARCHAR2(50), 
	"CS_MS" NVARCHAR2(50), 
	"CS_HS" NVARCHAR2(50), 
	"CS_UNIV" NVARCHAR2(50), 
	"CS_CAREER" NVARCHAR2(100), 
	"CS_JY" NUMBER, 
	"CS_PIC" NVARCHAR2(200)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "TOM"."COACHING_STAFF"."CS_CODE" IS '스탭코드';
   COMMENT ON COLUMN "TOM"."COACHING_STAFF"."T_CODE" IS '구단코드';
   COMMENT ON COLUMN "TOM"."COACHING_STAFF"."CD_CODE" IS '코칭담당코드';
   COMMENT ON COLUMN "TOM"."COACHING_STAFF"."CP_CODE" IS '코칭포지션코드';
   COMMENT ON COLUMN "TOM"."COACHING_STAFF"."CS_NAME" IS '이름';
   COMMENT ON COLUMN "TOM"."COACHING_STAFF"."CS_BIRTH" IS '생년월일';
   COMMENT ON COLUMN "TOM"."COACHING_STAFF"."CS_BN" IS '등번호';
   COMMENT ON COLUMN "TOM"."COACHING_STAFF"."CS_HEIGHT" IS '신장';
   COMMENT ON COLUMN "TOM"."COACHING_STAFF"."CS_WEIGHT" IS '체중';
   COMMENT ON COLUMN "TOM"."COACHING_STAFF"."CS_ES" IS '출신초';
   COMMENT ON COLUMN "TOM"."COACHING_STAFF"."CS_MS" IS '출신중';
   COMMENT ON COLUMN "TOM"."COACHING_STAFF"."CS_HS" IS '출신고';
   COMMENT ON COLUMN "TOM"."COACHING_STAFF"."CS_UNIV" IS '출신대';
   COMMENT ON COLUMN "TOM"."COACHING_STAFF"."CS_CAREER" IS '경력';
   COMMENT ON COLUMN "TOM"."COACHING_STAFF"."CS_JY" IS '입단년도';
   COMMENT ON COLUMN "TOM"."COACHING_STAFF"."CS_PIC" IS '코치사진';
   COMMENT ON TABLE "TOM"."COACHING_STAFF"  IS '코칭스태프';
