--------------------------------------------------------
--  Constraints for Table FC_KIND
--------------------------------------------------------

  ALTER TABLE "TOM"."FC_KIND" MODIFY ("FC_CODE" NOT NULL ENABLE);
  ALTER TABLE "TOM"."FC_KIND" MODIFY ("FC_KIND" NOT NULL ENABLE);
  ALTER TABLE "TOM"."FC_KIND" ADD CONSTRAINT "PK_FC_KIND" PRIMARY KEY ("FC_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
