--------------------------------------------------------
--  DDL for Table HIT_RECORDS
--------------------------------------------------------

  CREATE TABLE "TOM"."HIT_RECORDS" 
   (	"HR_CODE" NUMBER, 
	"PL_CODE" NUMBER, 
	"HR_YEAR" NUMBER, 
	"HR_AVG" NUMBER, 
	"HR_G" NUMBER, 
	"HR_PA" NUMBER, 
	"HR_AB" NUMBER, 
	"HR_R" NUMBER, 
	"HR_H" NUMBER, 
	"HR_2B" NUMBER, 
	"HR_3B" NUMBER, 
	"HR_HR" NUMBER, 
	"HR_TB" NUMBER, 
	"HR_RBI" NUMBER, 
	"BR_SB" NUMBER, 
	"HR_CS" NUMBER, 
	"HR_SAC" NUMBER, 
	"HR_SF" NUMBER, 
	"HR_BB" NUMBER, 
	"HR_IBB" NUMBER, 
	"HR_HBP" NUMBER, 
	"HR_SO" NUMBER, 
	"HR_GDP" NUMBER, 
	"HR_SLG" NUMBER, 
	"HR_OBP" NUMBER, 
	"HR_E" NUMBER, 
	"HR_SBP" NUMBER, 
	"HR_MH" NUMBER, 
	"HR_OPS" NUMBER, 
	"HR_RISP" NUMBER, 
	"HR_PHBA" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_CODE" IS '타자성적코드';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."PL_CODE" IS '선수코드';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_YEAR" IS '연도';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_AVG" IS '타율';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_G" IS '경기';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_PA" IS '타석';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_AB" IS '타수';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_R" IS '득점';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_H" IS '안타';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_2B" IS '2루타';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_3B" IS '3루타';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_HR" IS '홈런';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_TB" IS '루타';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_RBI" IS '타점';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."BR_SB" IS '도루';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_CS" IS '도루실패';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_SAC" IS '희생번트';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_SF" IS '희생플라이';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_BB" IS '볼넷';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_IBB" IS '고의4구';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_HBP" IS '사구';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_SO" IS '삼진';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_GDP" IS '병살';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_SLG" IS '장타';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_OBP" IS '출루율';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_E" IS '실책';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_SBP" IS '도루성공율';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_MH" IS '멀티히트';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_OPS" IS '출루율+장타율';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_RISP" IS '득점권타율';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_PHBA" IS '대타타율';
   COMMENT ON TABLE "TOM"."HIT_RECORDS"  IS '타자성적';
