--------------------------------------------------------
--  DDL for Table P_PT
--------------------------------------------------------

  CREATE TABLE "TOM"."P_PT" 
   (	"PT_CODE" NUMBER, 
	"PT_NAME" NVARCHAR2(4)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "TOM"."P_PT"."PT_CODE" IS '투타코드';
   COMMENT ON COLUMN "TOM"."P_PT"."PT_NAME" IS '투타구분명';
   COMMENT ON TABLE "TOM"."P_PT"  IS '투타정보';
