--------------------------------------------------------
--  Constraints for Table PITCH_RECORDS
--------------------------------------------------------

  ALTER TABLE "TOM"."PITCH_RECORDS" MODIFY ("PR_CODE" NOT NULL ENABLE);
  ALTER TABLE "TOM"."PITCH_RECORDS" MODIFY ("PL_CODE" NOT NULL ENABLE);
  ALTER TABLE "TOM"."PITCH_RECORDS" ADD CONSTRAINT "PK_PITCH_RECORDS" PRIMARY KEY ("PR_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
