--------------------------------------------------------
--  DDL for Table PITCH_RECORDS
--------------------------------------------------------

  CREATE TABLE "TOM"."PITCH_RECORDS" 
   (	"PR_CODE" NUMBER, 
	"PL_CODE" NUMBER, 
	"PR_YEAR" NUMBER, 
	"PR_ERA" NUMBER, 
	"PR_G" NUMBER, 
	"PR_CG" NUMBER, 
	"PR_SHO" NUMBER, 
	"PR_W" NUMBER, 
	"PR_L" NUMBER, 
	"PR_SV" NUMBER, 
	"PR_HLD" NUMBER, 
	"PR_WPCT" NUMBER, 
	"PR_TBF" NUMBER, 
	"PR_NP" NUMBER, 
	"PR_IP" NUMBER, 
	"PR_H" NUMBER, 
	"PR_2B" NUMBER, 
	"PR_3B" NUMBER, 
	"PR_HR" NUMBER, 
	"PR_SAC" NUMBER, 
	"PR_SF" NUMBER, 
	"PR_BB" NUMBER, 
	"PR_IBB" NUMBER, 
	"PR_SO" NUMBER, 
	"PR_WP" NUMBER, 
	"PR_BK" NUMBER, 
	"PR_R" NUMBER, 
	"PR_ER" NUMBER, 
	"PR_BSV" NUMBER, 
	"PR_WHIP" NUMBER, 
	"PR_AVG" NUMBER, 
	"PR_QS" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_CODE" IS '투수성적코드';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PL_CODE" IS '선수코드';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_YEAR" IS '연도';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_ERA" IS '평균자책점';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_G" IS '경기';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_CG" IS '완투';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_SHO" IS '완봉';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_W" IS '승';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_L" IS '패';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_SV" IS '세이브';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_HLD" IS '홀드';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_WPCT" IS '승률';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_TBF" IS '타자수';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_NP" IS '투구수';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_IP" IS '이닝';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_H" IS '피안타';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_2B" IS '2루타';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_3B" IS '3루타';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_HR" IS '피홈런';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_SAC" IS '희생번트';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_SF" IS '희생플라이';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_BB" IS '볼넷';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_IBB" IS '고의4구';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_SO" IS '탈삼진';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_WP" IS '폭투';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_BK" IS '보크';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_R" IS '실점';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_ER" IS '자책점';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_BSV" IS '블론세이브';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_WHIP" IS '이닝당출루허용률';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_AVG" IS '피안타율';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_QS" IS '퀄리티스타트';
   COMMENT ON TABLE "TOM"."PITCH_RECORDS"  IS '투수성적';
