--------------------------------------------------------
--  Constraints for Table PLAYER
--------------------------------------------------------

  ALTER TABLE "TOM"."PLAYER" MODIFY ("PL_CODE" NOT NULL ENABLE);
  ALTER TABLE "TOM"."PLAYER" MODIFY ("T_CODE" NOT NULL ENABLE);
  ALTER TABLE "TOM"."PLAYER" MODIFY ("PP_CODE" NOT NULL ENABLE);
  ALTER TABLE "TOM"."PLAYER" MODIFY ("PT_CODE" NOT NULL ENABLE);
  ALTER TABLE "TOM"."PLAYER" MODIFY ("PS_CODE" NOT NULL ENABLE);
  ALTER TABLE "TOM"."PLAYER" MODIFY ("PL_NAME" NOT NULL ENABLE);
  ALTER TABLE "TOM"."PLAYER" MODIFY ("PL_BIRTH" NOT NULL ENABLE);
  ALTER TABLE "TOM"."PLAYER" MODIFY ("PL_HEIGHT" NOT NULL ENABLE);
  ALTER TABLE "TOM"."PLAYER" MODIFY ("PL_WEIGHT" NOT NULL ENABLE);
  ALTER TABLE "TOM"."PLAYER" MODIFY ("PL_JYEAR" NOT NULL ENABLE);
