--------------------------------------------------------
--  DDL for Table PLAYER
--------------------------------------------------------

  CREATE TABLE "TOM"."PLAYER" 
   (	"PL_CODE" NUMBER, 
	"T_CODE" NUMBER, 
	"PP_CODE" NUMBER, 
	"PT_CODE" NUMBER, 
	"PS_CODE" NUMBER, 
	"PL_NAME" NVARCHAR2(20), 
	"PL_BIRTH" DATE, 
	"PL_HEIGHT" NUMBER, 
	"PL_WEIGHT" NUMBER, 
	"PL_BN" NUMBER, 
	"PL_ES" NVARCHAR2(50), 
	"PL_MS" NVARCHAR2(50), 
	"PL_HS" NVARCHAR2(50), 
	"PL_UNIV" NVARCHAR2(50), 
	"PL_FOR" NVARCHAR2(20), 
	"PL_CAREER" NVARCHAR2(100), 
	"PL_JYEAR" NUMBER, 
	"PL_NRANK" NVARCHAR2(100), 
	"PL_AS" NUMBER, 
	"PL_PIC" NVARCHAR2(200)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "TOM"."PLAYER"."PL_CODE" IS '선수코드';
   COMMENT ON COLUMN "TOM"."PLAYER"."T_CODE" IS '구단코드';
   COMMENT ON COLUMN "TOM"."PLAYER"."PP_CODE" IS '선수포지션코드';
   COMMENT ON COLUMN "TOM"."PLAYER"."PT_CODE" IS '투타코드';
   COMMENT ON COLUMN "TOM"."PLAYER"."PS_CODE" IS '선수상태코드';
   COMMENT ON COLUMN "TOM"."PLAYER"."PL_NAME" IS '이름';
   COMMENT ON COLUMN "TOM"."PLAYER"."PL_BIRTH" IS '생년월일';
   COMMENT ON COLUMN "TOM"."PLAYER"."PL_HEIGHT" IS '신장';
   COMMENT ON COLUMN "TOM"."PLAYER"."PL_WEIGHT" IS '체중';
   COMMENT ON COLUMN "TOM"."PLAYER"."PL_BN" IS '등번호';
   COMMENT ON COLUMN "TOM"."PLAYER"."PL_ES" IS '출신초';
   COMMENT ON COLUMN "TOM"."PLAYER"."PL_MS" IS '출신중';
   COMMENT ON COLUMN "TOM"."PLAYER"."PL_HS" IS '출신고';
   COMMENT ON COLUMN "TOM"."PLAYER"."PL_UNIV" IS '출신대';
   COMMENT ON COLUMN "TOM"."PLAYER"."PL_FOR" IS '군팀';
   COMMENT ON COLUMN "TOM"."PLAYER"."PL_CAREER" IS '경력';
   COMMENT ON COLUMN "TOM"."PLAYER"."PL_JYEAR" IS '입단년도';
   COMMENT ON COLUMN "TOM"."PLAYER"."PL_NRANK" IS '지명순위';
   COMMENT ON COLUMN "TOM"."PLAYER"."PL_AS" IS '연봉';
   COMMENT ON COLUMN "TOM"."PLAYER"."PL_PIC" IS '선수사진';
   COMMENT ON TABLE "TOM"."PLAYER"  IS '선수';
