--------------------------------------------------------
--  DDL for Table SP_KIND
--------------------------------------------------------

  CREATE TABLE "TOM"."SP_KIND" 
   (	"SK_CODE" NUMBER, 
	"SK_NAME" NVARCHAR2(10)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "TOM"."SP_KIND"."SK_CODE" IS '협찬분야코드';
   COMMENT ON COLUMN "TOM"."SP_KIND"."SK_NAME" IS '분야명';
   COMMENT ON TABLE "TOM"."SP_KIND"  IS '스폰서협찬분야';
