--------------------------------------------------------
--  Constraints for Table SPONSER
--------------------------------------------------------

  ALTER TABLE "TOM"."SPONSER" MODIFY ("SP_CODE" NOT NULL ENABLE);
  ALTER TABLE "TOM"."SPONSER" MODIFY ("T_CODE" NOT NULL ENABLE);
  ALTER TABLE "TOM"."SPONSER" MODIFY ("SK_CODE" NOT NULL ENABLE);
  ALTER TABLE "TOM"."SPONSER" MODIFY ("SP_NAME" NOT NULL ENABLE);
  ALTER TABLE "TOM"."SPONSER" ADD CONSTRAINT "PK_SPONSER" PRIMARY KEY ("SP_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
