--------------------------------------------------------
--  DDL for Table SPONSER
--------------------------------------------------------

  CREATE TABLE "TOM"."SPONSER" 
   (	"SP_CODE" NUMBER, 
	"T_CODE" NUMBER, 
	"SK_CODE" NUMBER, 
	"SP_NAME" NVARCHAR2(20), 
	"SP_AMOUNT" NUMBER, 
	"SP_LOGO" NVARCHAR2(200)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "TOM"."SPONSER"."SP_CODE" IS '스폰서코드';
   COMMENT ON COLUMN "TOM"."SPONSER"."T_CODE" IS '구단코드';
   COMMENT ON COLUMN "TOM"."SPONSER"."SK_CODE" IS '협찬분야코드';
   COMMENT ON COLUMN "TOM"."SPONSER"."SP_NAME" IS '기업명';
   COMMENT ON COLUMN "TOM"."SPONSER"."SP_AMOUNT" IS '금액';
   COMMENT ON COLUMN "TOM"."SPONSER"."SP_LOGO" IS '로고
';
   COMMENT ON TABLE "TOM"."SPONSER"  IS '구단스폰서';
