--------------------------------------------------------
--  DDL for Table ST_FACILITY
--------------------------------------------------------

  CREATE TABLE "TOM"."ST_FACILITY" 
   (	"SF_CODE" NUMBER, 
	"FC_CODE" NUMBER, 
	"SF_NAME" NVARCHAR2(20), 
	"SF_PIC" NVARCHAR2(200), 
	"SF_EX" NVARCHAR2(500), 
	"SF_CHARGE" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "TOM"."ST_FACILITY"."SF_CODE" IS '시설코드';
   COMMENT ON COLUMN "TOM"."ST_FACILITY"."FC_CODE" IS '시설분류코드';
   COMMENT ON COLUMN "TOM"."ST_FACILITY"."SF_NAME" IS '시설이름';
   COMMENT ON COLUMN "TOM"."ST_FACILITY"."SF_PIC" IS '시설사진';
   COMMENT ON COLUMN "TOM"."ST_FACILITY"."SF_EX" IS '시설설명';
   COMMENT ON COLUMN "TOM"."ST_FACILITY"."SF_CHARGE" IS '시설이용료';
   COMMENT ON TABLE "TOM"."ST_FACILITY"  IS '구장시설';
