--------------------------------------------------------
--  Constraints for Table ST_FACILITY
--------------------------------------------------------

  ALTER TABLE "TOM"."ST_FACILITY" MODIFY ("SF_CODE" NOT NULL ENABLE);
  ALTER TABLE "TOM"."ST_FACILITY" MODIFY ("FC_CODE" NOT NULL ENABLE);
  ALTER TABLE "TOM"."ST_FACILITY" MODIFY ("SF_NAME" NOT NULL ENABLE);
  ALTER TABLE "TOM"."ST_FACILITY" ADD CONSTRAINT "PK_ST_FACILITY" PRIMARY KEY ("SF_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
