--------------------------------------------------------
--  Constraints for Table STADIUM
--------------------------------------------------------

  ALTER TABLE "TOM"."STADIUM" MODIFY ("ST_CODE" NOT NULL ENABLE);
  ALTER TABLE "TOM"."STADIUM" MODIFY ("T_CODE" NOT NULL ENABLE);
  ALTER TABLE "TOM"."STADIUM" MODIFY ("ST_NAME" NOT NULL ENABLE);
  ALTER TABLE "TOM"."STADIUM" MODIFY ("ST_ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "TOM"."STADIUM" MODIFY ("SF_CODE" NOT NULL ENABLE);
  ALTER TABLE "TOM"."STADIUM" ADD CONSTRAINT "PK_STADIUM" PRIMARY KEY ("ST_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
