--------------------------------------------------------
--  DDL for Table STADIUM
--------------------------------------------------------

  CREATE TABLE "TOM"."STADIUM" 
   (	"ST_CODE" NUMBER, 
	"T_CODE" NUMBER, 
	"ST_NAME" NVARCHAR2(10), 
	"ST_ADDRESS" NVARCHAR2(100), 
	"ST_PH" NVARCHAR2(20), 
	"ST_FAX" NVARCHAR2(20), 
	"ST_SPIC" NVARCHAR2(200), 
	"ST_SEATS" NUMBER, 
	"ST_AREA" NUMBER, 
	"SF_CODE" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "TOM"."STADIUM"."ST_CODE" IS '구장코드';
   COMMENT ON COLUMN "TOM"."STADIUM"."T_CODE" IS '구단코드';
   COMMENT ON COLUMN "TOM"."STADIUM"."ST_NAME" IS '구장명';
   COMMENT ON COLUMN "TOM"."STADIUM"."ST_ADDRESS" IS '주소';
   COMMENT ON COLUMN "TOM"."STADIUM"."ST_PH" IS '전화번호';
   COMMENT ON COLUMN "TOM"."STADIUM"."ST_FAX" IS '팩스';
   COMMENT ON COLUMN "TOM"."STADIUM"."ST_SPIC" IS '좌석배치도';
   COMMENT ON COLUMN "TOM"."STADIUM"."ST_SEATS" IS '좌석수';
   COMMENT ON COLUMN "TOM"."STADIUM"."ST_AREA" IS '면적';
   COMMENT ON COLUMN "TOM"."STADIUM"."SF_CODE" IS '시설코드';
   COMMENT ON TABLE "TOM"."STADIUM"  IS '구장';
