--------------------------------------------------------
--  Constraints for Table TEAM_RECORDS
--------------------------------------------------------

  ALTER TABLE "TOM"."TEAM_RECORDS" MODIFY ("TR_CODE" NOT NULL ENABLE);
  ALTER TABLE "TOM"."TEAM_RECORDS" MODIFY ("T_CODE" NOT NULL ENABLE);
  ALTER TABLE "TOM"."TEAM_RECORDS" ADD CONSTRAINT "PK_TEAM_RECORDS" PRIMARY KEY ("TR_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
