--------------------------------------------------------
--  DDL for Table TEAM
--------------------------------------------------------

  CREATE TABLE "TOM"."TEAM" 
   (	"T_CODE" NUMBER, 
	"T_NAME" NVARCHAR2(10), 
	"T_HTOWN" NVARCHAR2(10), 
	"T_OWNER" NVARCHAR2(10), 
	"T_FYEAR" NUMBER, 
	"T_EMBLEM" NVARCHAR2(200), 
	"T_LOGO" NVARCHAR2(200), 
	"T_SYMBOL" NVARCHAR2(200), 
	"T_MASCOT" NVARCHAR2(200)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "TOM"."TEAM"."T_CODE" IS '구단코드';
   COMMENT ON COLUMN "TOM"."TEAM"."T_NAME" IS '구단명';
   COMMENT ON COLUMN "TOM"."TEAM"."T_HTOWN" IS '연고지';
   COMMENT ON COLUMN "TOM"."TEAM"."T_OWNER" IS '구단주';
   COMMENT ON COLUMN "TOM"."TEAM"."T_FYEAR" IS '창단년도';
   COMMENT ON COLUMN "TOM"."TEAM"."T_EMBLEM" IS '엠블럼';
   COMMENT ON COLUMN "TOM"."TEAM"."T_LOGO" IS '구단로고';
   COMMENT ON COLUMN "TOM"."TEAM"."T_SYMBOL" IS '구단상징';
   COMMENT ON COLUMN "TOM"."TEAM"."T_MASCOT" IS '구단마스코트';
   COMMENT ON TABLE "TOM"."TEAM"  IS '구단';
