--------------------------------------------------------
--  DDL for Table TEAM_RECORDS
--------------------------------------------------------

  CREATE TABLE "TOM"."TEAM_RECORDS" 
   (	"TR_CODE" NUMBER, 
	"T_CODE" NUMBER, 
	"TR_YEAR" NUMBER, 
	"TR_G" NUMBER, 
	"TR_W" NUMBER, 
	"TR_D" NUMBER, 
	"TR_L" NUMBER, 
	"TR_WPCT" NUMBER, 
	"TR_RANK" NUMBER, 
	"TR_RA" NUMBER, 
	"TR_RL" NUMBER, 
	"TR_HR" NUMBER, 
	"TR_SB" NUMBER, 
	"TR_AVG" NUMBER, 
	"TR_ERA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "TOM"."TEAM_RECORDS"."TR_CODE" IS '팀성적코드';
   COMMENT ON COLUMN "TOM"."TEAM_RECORDS"."T_CODE" IS '구단코드';
   COMMENT ON COLUMN "TOM"."TEAM_RECORDS"."TR_YEAR" IS '연도';
   COMMENT ON COLUMN "TOM"."TEAM_RECORDS"."TR_G" IS '경기';
   COMMENT ON COLUMN "TOM"."TEAM_RECORDS"."TR_W" IS '승';
   COMMENT ON COLUMN "TOM"."TEAM_RECORDS"."TR_D" IS '무';
   COMMENT ON COLUMN "TOM"."TEAM_RECORDS"."TR_L" IS '패';
   COMMENT ON COLUMN "TOM"."TEAM_RECORDS"."TR_WPCT" IS '승률';
   COMMENT ON COLUMN "TOM"."TEAM_RECORDS"."TR_RANK" IS '순위';
   COMMENT ON COLUMN "TOM"."TEAM_RECORDS"."TR_RA" IS '득점';
   COMMENT ON COLUMN "TOM"."TEAM_RECORDS"."TR_RL" IS '실점';
   COMMENT ON COLUMN "TOM"."TEAM_RECORDS"."TR_HR" IS '홈런';
   COMMENT ON COLUMN "TOM"."TEAM_RECORDS"."TR_SB" IS '도루';
   COMMENT ON COLUMN "TOM"."TEAM_RECORDS"."TR_AVG" IS '타율';
   COMMENT ON COLUMN "TOM"."TEAM_RECORDS"."TR_ERA" IS '방어율';
   COMMENT ON TABLE "TOM"."TEAM_RECORDS"  IS '팀성적';
