--------------------------------------------------------
--  파일이 생성됨 - 화요일-3월-24-2020   
--------------------------------------------------------
@D:\★\ex-im\2\TEAM_RECORDS.sql
@D:\★\ex-im\2\TEAM.sql
@D:\★\ex-im\2\STADIUM.sql
@D:\★\ex-im\2\SPONSER.sql
@D:\★\ex-im\2\ST_FACILITY.sql
@D:\★\ex-im\2\SP_KIND.sql
@D:\★\ex-im\2\PLAYER.sql
@D:\★\ex-im\2\PITCH_RECORDS.sql
@D:\★\ex-im\2\P_STATE.sql
@D:\★\ex-im\2\P_PT.sql
@D:\★\ex-im\2\P_POSITION.sql
@D:\★\ex-im\2\HIT_RECORDS.sql
@D:\★\ex-im\2\FC_KIND.sql
@D:\★\ex-im\2\COACHING_STAFF.sql
@D:\★\ex-im\2\C_POSITION.sql
@D:\★\ex-im\2\C_DETAIL.sql
@D:\★\ex-im\2\ADMIN.sql
--@D:\★\ex-im\2\TEAM_RECORDS_DATA_TABLE.xlsx
--@D:\★\ex-im\2\TEAM_DATA_TABLE.xlsx
--@D:\★\ex-im\2\STADIUM_DATA_TABLE.xlsx
--@D:\★\ex-im\2\SPONSER_DATA_TABLE.xlsx
--@D:\★\ex-im\2\ST_FACILITY_DATA_TABLE.xlsx
--@D:\★\ex-im\2\SP_KIND_DATA_TABLE.xlsx
--@D:\★\ex-im\2\PLAYER_DATA_TABLE.xlsx
--@D:\★\ex-im\2\PITCH_RECORDS_DATA_TABLE.xlsx
--@D:\★\ex-im\2\P_STATE_DATA_TABLE.xlsx
--@D:\★\ex-im\2\P_PT_DATA_TABLE.xlsx
--@D:\★\ex-im\2\P_POSITION_DATA_TABLE.xlsx
--@D:\★\ex-im\2\HIT_RECORDS_DATA_TABLE.xlsx
--@D:\★\ex-im\2\FC_KIND_DATA_TABLE.xlsx
--@D:\★\ex-im\2\COACHING_STAFF_DATA_TABLE.xlsx
--@D:\★\ex-im\2\C_POSITION_DATA_TABLE.xlsx
--@D:\★\ex-im\2\C_DETAIL_DATA_TABLE.xlsx
--@D:\★\ex-im\2\ADMIN_DATA_TABLE.xlsx
@D:\★\ex-im\2\PK_TEAM_RECORDS.sql
@D:\★\ex-im\2\PK_TEAM.sql
@D:\★\ex-im\2\PK_STADIUM.sql
@D:\★\ex-im\2\PK_SPONSER.sql
@D:\★\ex-im\2\PK_ST_FACILITY.sql
@D:\★\ex-im\2\PK_SP_KIND.sql
@D:\★\ex-im\2\PK_PITCH_RECORDS.sql
@D:\★\ex-im\2\PK_P_PT.sql
@D:\★\ex-im\2\PK_HIT_RECORDS.sql
@D:\★\ex-im\2\PK_FC_KIND.sql
@D:\★\ex-im\2\PK_COACHING_STAFF.sql
@D:\★\ex-im\2\PK_C_POSITION.sql
@D:\★\ex-im\2\PK_C_DETAIL.sql
@D:\★\ex-im\2\PK_ADMIN.sql
@D:\★\ex-im\2\TEAM_RECORDS_CONSTRAINT.sql
@D:\★\ex-im\2\TEAM_CONSTRAINT.sql
@D:\★\ex-im\2\STADIUM_CONSTRAINT.sql
@D:\★\ex-im\2\SPONSER_CONSTRAINT.sql
@D:\★\ex-im\2\ST_FACILITY_CONSTRAINT.sql
@D:\★\ex-im\2\SP_KIND_CONSTRAINT.sql
@D:\★\ex-im\2\PLAYER_CONSTRAINT.sql
@D:\★\ex-im\2\PITCH_RECORDS_CONSTRAINT.sql
@D:\★\ex-im\2\P_STATE_CONSTRAINT.sql
@D:\★\ex-im\2\P_PT_CONSTRAINT.sql
@D:\★\ex-im\2\P_POSITION_CONSTRAINT.sql
@D:\★\ex-im\2\HIT_RECORDS_CONSTRAINT.sql
@D:\★\ex-im\2\FC_KIND_CONSTRAINT.sql
@D:\★\ex-im\2\COACHING_STAFF_CONSTRAINT.sql
@D:\★\ex-im\2\C_POSITION_CONSTRAINT.sql
@D:\★\ex-im\2\C_DETAIL_CONSTRAINT.sql
@D:\★\ex-im\2\ADMIN_CONSTRAINT.sql
