--------------------------------------------------------
--  Constraints for Table ADMIN
--------------------------------------------------------

  ALTER TABLE "TOM"."ADMIN" MODIFY ("AD_ID" NOT NULL ENABLE);
  ALTER TABLE "TOM"."ADMIN" MODIFY ("T_CODE" NOT NULL ENABLE);
  ALTER TABLE "TOM"."ADMIN" MODIFY ("AD_PW" NOT NULL ENABLE);
  ALTER TABLE "TOM"."ADMIN" MODIFY ("AD_NAME" NOT NULL ENABLE);
  ALTER TABLE "TOM"."ADMIN" ADD CONSTRAINT "PK_ADMIN" PRIMARY KEY ("AD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
