--------------------------------------------------------
--  Constraints for Table CHEERING_SQUAD
--------------------------------------------------------

  ALTER TABLE "TOM"."CHEERING_SQUAD" MODIFY ("C_CODE" NOT NULL ENABLE);
  ALTER TABLE "TOM"."CHEERING_SQUAD" MODIFY ("T_CODE" NOT NULL ENABLE);
  ALTER TABLE "TOM"."CHEERING_SQUAD" MODIFY ("C_NAME" NOT NULL ENABLE);
  ALTER TABLE "TOM"."CHEERING_SQUAD" MODIFY ("C_BIRTH" NOT NULL ENABLE);
  ALTER TABLE "TOM"."CHEERING_SQUAD" MODIFY ("C_HEIGHT" NOT NULL ENABLE);
  ALTER TABLE "TOM"."CHEERING_SQUAD" ADD CONSTRAINT "PK_CHEERING_SQUAD" PRIMARY KEY ("C_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
