--------------------------------------------------------
--  DDL for Table CHEERING_SQUAD
--------------------------------------------------------

  CREATE TABLE "TOM"."CHEERING_SQUAD" 
   (	"C_CODE" NUMBER, 
	"T_CODE" NUMBER, 
	"C_NAME" NVARCHAR2(10), 
	"C_BIRTH" DATE, 
	"C_HEIGHT" NUMBER, 
	"C_PIC" NVARCHAR2(200), 
	"C_NICK" NVARCHAR2(20), 
	"C_HOBBY" NVARCHAR2(50), 
	"C_COM" NVARCHAR2(500)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "TOM"."CHEERING_SQUAD"."C_CODE" IS '응원단코드';
   COMMENT ON COLUMN "TOM"."CHEERING_SQUAD"."T_CODE" IS '구단코드';
   COMMENT ON COLUMN "TOM"."CHEERING_SQUAD"."C_NAME" IS '이름';
   COMMENT ON COLUMN "TOM"."CHEERING_SQUAD"."C_BIRTH" IS '생년월일';
   COMMENT ON COLUMN "TOM"."CHEERING_SQUAD"."C_HEIGHT" IS '신장';
   COMMENT ON COLUMN "TOM"."CHEERING_SQUAD"."C_PIC" IS '응원단사진';
   COMMENT ON COLUMN "TOM"."CHEERING_SQUAD"."C_NICK" IS '별명';
   COMMENT ON COLUMN "TOM"."CHEERING_SQUAD"."C_HOBBY" IS '취미';
   COMMENT ON COLUMN "TOM"."CHEERING_SQUAD"."C_COM" IS '시즌각오';
   COMMENT ON TABLE "TOM"."CHEERING_SQUAD"  IS '응원단';
