--------------------------------------------------------
--  Constraints for Table C_DETAIL
--------------------------------------------------------

  ALTER TABLE "TOM"."C_DETAIL" MODIFY ("CD_CODE" NOT NULL ENABLE);
  ALTER TABLE "TOM"."C_DETAIL" MODIFY ("CD_NAME" NOT NULL ENABLE);
  ALTER TABLE "TOM"."C_DETAIL" ADD CONSTRAINT "PK_C_DETAIL" PRIMARY KEY ("CD_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table C_POSITION
--------------------------------------------------------

  ALTER TABLE "TOM"."C_POSITION" MODIFY ("CP_CODE" NOT NULL ENABLE);
  ALTER TABLE "TOM"."C_POSITION" MODIFY ("CP_NAME" NOT NULL ENABLE);
  ALTER TABLE "TOM"."C_POSITION" ADD CONSTRAINT "PK_C_POSITION" PRIMARY KEY ("CP_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COACHING_STAFF
--------------------------------------------------------

  ALTER TABLE "TOM"."COACHING_STAFF" MODIFY ("CS_CODE" NOT NULL ENABLE);
  ALTER TABLE "TOM"."COACHING_STAFF" MODIFY ("T_CODE" NOT NULL ENABLE);
  ALTER TABLE "TOM"."COACHING_STAFF" MODIFY ("CD_CODE" NOT NULL ENABLE);
  ALTER TABLE "TOM"."COACHING_STAFF" MODIFY ("CP_CODE" NOT NULL ENABLE);
  ALTER TABLE "TOM"."COACHING_STAFF" MODIFY ("CS_NAME" NOT NULL ENABLE);
  ALTER TABLE "TOM"."COACHING_STAFF" MODIFY ("CS_BIRTH" NOT NULL ENABLE);
  ALTER TABLE "TOM"."COACHING_STAFF" MODIFY ("CS_BN" NOT NULL ENABLE);
  ALTER TABLE "TOM"."COACHING_STAFF" MODIFY ("CS_HEIGHT" NOT NULL ENABLE);
  ALTER TABLE "TOM"."COACHING_STAFF" MODIFY ("CS_WEIGHT" NOT NULL ENABLE);
  ALTER TABLE "TOM"."COACHING_STAFF" MODIFY ("CS_JY" NOT NULL ENABLE);
  ALTER TABLE "TOM"."COACHING_STAFF" ADD CONSTRAINT "PK_COACHING_STAFF" PRIMARY KEY ("CS_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FC_KIND
--------------------------------------------------------

  ALTER TABLE "TOM"."FC_KIND" MODIFY ("FC_CODE" NOT NULL ENABLE);
  ALTER TABLE "TOM"."FC_KIND" MODIFY ("FC_KIND" NOT NULL ENABLE);
  ALTER TABLE "TOM"."FC_KIND" ADD CONSTRAINT "PK_FC_KIND" PRIMARY KEY ("FC_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table HIT_RECORDS
--------------------------------------------------------

  ALTER TABLE "TOM"."HIT_RECORDS" MODIFY ("HR_CODE" NOT NULL ENABLE);
  ALTER TABLE "TOM"."HIT_RECORDS" MODIFY ("PL_CODE" NOT NULL ENABLE);
  ALTER TABLE "TOM"."HIT_RECORDS" ADD CONSTRAINT "PK_HIT_RECORDS" PRIMARY KEY ("HR_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table P_POSITION
--------------------------------------------------------

  ALTER TABLE "TOM"."P_POSITION" MODIFY ("PP_CODE" NOT NULL ENABLE);
  ALTER TABLE "TOM"."P_POSITION" MODIFY ("PP_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table P_PT
--------------------------------------------------------

  ALTER TABLE "TOM"."P_PT" MODIFY ("PT_CODE" NOT NULL ENABLE);
  ALTER TABLE "TOM"."P_PT" MODIFY ("PT_NAME" NOT NULL ENABLE);
  ALTER TABLE "TOM"."P_PT" ADD CONSTRAINT "PK_P_PT" PRIMARY KEY ("PT_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table P_STATE
--------------------------------------------------------

  ALTER TABLE "TOM"."P_STATE" MODIFY ("PS_CODE" NOT NULL ENABLE);
  ALTER TABLE "TOM"."P_STATE" MODIFY ("PS_STATE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PITCH_RECORDS
--------------------------------------------------------

  ALTER TABLE "TOM"."PITCH_RECORDS" MODIFY ("PR_CODE" NOT NULL ENABLE);
  ALTER TABLE "TOM"."PITCH_RECORDS" MODIFY ("PL_CODE" NOT NULL ENABLE);
  ALTER TABLE "TOM"."PITCH_RECORDS" ADD CONSTRAINT "PK_PITCH_RECORDS" PRIMARY KEY ("PR_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PLAYER
--------------------------------------------------------

  ALTER TABLE "TOM"."PLAYER" MODIFY ("PL_CODE" NOT NULL ENABLE);
  ALTER TABLE "TOM"."PLAYER" MODIFY ("T_CODE" NOT NULL ENABLE);
  ALTER TABLE "TOM"."PLAYER" MODIFY ("PP_CODE" NOT NULL ENABLE);
  ALTER TABLE "TOM"."PLAYER" MODIFY ("PT_CODE" NOT NULL ENABLE);
  ALTER TABLE "TOM"."PLAYER" MODIFY ("PS_CODE" NOT NULL ENABLE);
  ALTER TABLE "TOM"."PLAYER" MODIFY ("PL_NAME" NOT NULL ENABLE);
  ALTER TABLE "TOM"."PLAYER" MODIFY ("PL_BIRTH" NOT NULL ENABLE);
  ALTER TABLE "TOM"."PLAYER" MODIFY ("PL_HEIGHT" NOT NULL ENABLE);
  ALTER TABLE "TOM"."PLAYER" MODIFY ("PL_WEIGHT" NOT NULL ENABLE);
  ALTER TABLE "TOM"."PLAYER" MODIFY ("PL_JYEAR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SP_KIND
--------------------------------------------------------

  ALTER TABLE "TOM"."SP_KIND" MODIFY ("SK_CODE" NOT NULL ENABLE);
  ALTER TABLE "TOM"."SP_KIND" MODIFY ("SK_NAME" NOT NULL ENABLE);
  ALTER TABLE "TOM"."SP_KIND" ADD CONSTRAINT "PK_SP_KIND" PRIMARY KEY ("SK_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SPONSER
--------------------------------------------------------

  ALTER TABLE "TOM"."SPONSER" MODIFY ("SP_CODE" NOT NULL ENABLE);
  ALTER TABLE "TOM"."SPONSER" MODIFY ("T_CODE" NOT NULL ENABLE);
  ALTER TABLE "TOM"."SPONSER" MODIFY ("SK_CODE" NOT NULL ENABLE);
  ALTER TABLE "TOM"."SPONSER" MODIFY ("SP_NAME" NOT NULL ENABLE);
  ALTER TABLE "TOM"."SPONSER" ADD CONSTRAINT "PK_SPONSER" PRIMARY KEY ("SP_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ST_FACILITY
--------------------------------------------------------

  ALTER TABLE "TOM"."ST_FACILITY" MODIFY ("SF_CODE" NOT NULL ENABLE);
  ALTER TABLE "TOM"."ST_FACILITY" MODIFY ("FC_CODE" NOT NULL ENABLE);
  ALTER TABLE "TOM"."ST_FACILITY" MODIFY ("SF_NAME" NOT NULL ENABLE);
  ALTER TABLE "TOM"."ST_FACILITY" ADD CONSTRAINT "PK_ST_FACILITY" PRIMARY KEY ("SF_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STADIUM
--------------------------------------------------------

  ALTER TABLE "TOM"."STADIUM" MODIFY ("ST_CODE" NOT NULL ENABLE);
  ALTER TABLE "TOM"."STADIUM" MODIFY ("T_CODE" NOT NULL ENABLE);
  ALTER TABLE "TOM"."STADIUM" MODIFY ("ST_NAME" NOT NULL ENABLE);
  ALTER TABLE "TOM"."STADIUM" MODIFY ("ST_ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "TOM"."STADIUM" MODIFY ("SF_CODE" NOT NULL ENABLE);
  ALTER TABLE "TOM"."STADIUM" ADD CONSTRAINT "PK_STADIUM" PRIMARY KEY ("ST_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TEAM
--------------------------------------------------------

  ALTER TABLE "TOM"."TEAM" MODIFY ("T_CODE" NOT NULL ENABLE);
  ALTER TABLE "TOM"."TEAM" MODIFY ("T_NAME" NOT NULL ENABLE);
  ALTER TABLE "TOM"."TEAM" MODIFY ("T_HTOWN" NOT NULL ENABLE);
  ALTER TABLE "TOM"."TEAM" MODIFY ("T_OWNER" NOT NULL ENABLE);
  ALTER TABLE "TOM"."TEAM" MODIFY ("T_FYEAR" NOT NULL ENABLE);
  ALTER TABLE "TOM"."TEAM" MODIFY ("T_SYMBOL" NOT NULL ENABLE);
  ALTER TABLE "TOM"."TEAM" ADD CONSTRAINT "PK_TEAM" PRIMARY KEY ("T_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TEAM_RECORDS
--------------------------------------------------------

  ALTER TABLE "TOM"."TEAM_RECORDS" MODIFY ("TR_CODE" NOT NULL ENABLE);
  ALTER TABLE "TOM"."TEAM_RECORDS" MODIFY ("T_CODE" NOT NULL ENABLE);
  ALTER TABLE "TOM"."TEAM_RECORDS" ADD CONSTRAINT "PK_TEAM_RECORDS" PRIMARY KEY ("TR_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
