--------------------------------------------------------
--  DDL for Table C_DETAIL
--------------------------------------------------------

  CREATE TABLE "TOM"."C_DETAIL" 
   (	"CD_CODE" NUMBER, 
	"CD_NAME" NCHAR(20)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "TOM"."C_DETAIL"."CD_CODE" IS '코칭담당코드';
   COMMENT ON COLUMN "TOM"."C_DETAIL"."CD_NAME" IS '코칭담당이름';
   COMMENT ON TABLE "TOM"."C_DETAIL"  IS '코칭담당';
--------------------------------------------------------
--  DDL for Table C_POSITION
--------------------------------------------------------

  CREATE TABLE "TOM"."C_POSITION" 
   (	"CP_CODE" NUMBER, 
	"CP_NAME" NVARCHAR2(10)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "TOM"."C_POSITION"."CP_CODE" IS '코칭포지션코드';
   COMMENT ON COLUMN "TOM"."C_POSITION"."CP_NAME" IS '코칭포지션명';
   COMMENT ON TABLE "TOM"."C_POSITION"  IS '코칭포지션';
--------------------------------------------------------
--  DDL for Table COACHING_STAFF
--------------------------------------------------------

  CREATE TABLE "TOM"."COACHING_STAFF" 
   (	"CS_CODE" NUMBER, 
	"T_CODE" NUMBER, 
	"CD_CODE" NUMBER, 
	"CP_CODE" NUMBER, 
	"CS_NAME" NVARCHAR2(20), 
	"CS_BIRTH" DATE, 
	"CS_BN" NUMBER, 
	"CS_HEIGHT" NUMBER, 
	"CS_WEIGHT" NUMBER, 
	"CS_ES" NVARCHAR2(50), 
	"CS_MS" NVARCHAR2(50), 
	"CS_HS" NVARCHAR2(50), 
	"CS_UNIV" NVARCHAR2(50), 
	"CS_CAREER" NVARCHAR2(100), 
	"CS_JY" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "TOM"."COACHING_STAFF"."CS_CODE" IS '스탭코드';
   COMMENT ON COLUMN "TOM"."COACHING_STAFF"."T_CODE" IS '구단코드';
   COMMENT ON COLUMN "TOM"."COACHING_STAFF"."CD_CODE" IS '코칭담당코드';
   COMMENT ON COLUMN "TOM"."COACHING_STAFF"."CP_CODE" IS '코칭포지션코드';
   COMMENT ON COLUMN "TOM"."COACHING_STAFF"."CS_NAME" IS '이름';
   COMMENT ON COLUMN "TOM"."COACHING_STAFF"."CS_BIRTH" IS '생년월일';
   COMMENT ON COLUMN "TOM"."COACHING_STAFF"."CS_BN" IS '등번호';
   COMMENT ON COLUMN "TOM"."COACHING_STAFF"."CS_HEIGHT" IS '신장';
   COMMENT ON COLUMN "TOM"."COACHING_STAFF"."CS_WEIGHT" IS '체중';
   COMMENT ON COLUMN "TOM"."COACHING_STAFF"."CS_ES" IS '출신초';
   COMMENT ON COLUMN "TOM"."COACHING_STAFF"."CS_MS" IS '출신중';
   COMMENT ON COLUMN "TOM"."COACHING_STAFF"."CS_HS" IS '출신고';
   COMMENT ON COLUMN "TOM"."COACHING_STAFF"."CS_UNIV" IS '출신대';
   COMMENT ON COLUMN "TOM"."COACHING_STAFF"."CS_CAREER" IS '경력';
   COMMENT ON COLUMN "TOM"."COACHING_STAFF"."CS_JY" IS '입단년도';
   COMMENT ON TABLE "TOM"."COACHING_STAFF"  IS '코칭스태프';
--------------------------------------------------------
--  DDL for Table FC_KIND
--------------------------------------------------------

  CREATE TABLE "TOM"."FC_KIND" 
   (	"FC_CODE" NUMBER, 
	"FC_KIND" NVARCHAR2(20)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "TOM"."FC_KIND"."FC_CODE" IS '시설분류코드';
   COMMENT ON COLUMN "TOM"."FC_KIND"."FC_KIND" IS '시설종류';
   COMMENT ON TABLE "TOM"."FC_KIND"  IS '시설분류';
--------------------------------------------------------
--  DDL for Table HIT_RECORDS
--------------------------------------------------------

  CREATE TABLE "TOM"."HIT_RECORDS" 
   (	"HR_CODE" NUMBER, 
	"PL_CODE" NUMBER, 
	"HR_YEAR" NUMBER, 
	"HR_AVG" NUMBER, 
	"HR_G" NUMBER, 
	"HR_PA" NUMBER, 
	"HR_AB" NUMBER, 
	"HR_R" NUMBER, 
	"HR_H" NUMBER, 
	"HR_2B" NUMBER, 
	"HR_3B" NUMBER, 
	"HR_HR" NUMBER, 
	"HR_TB" NUMBER, 
	"HR_RBI" NUMBER, 
	"BR_SB" NUMBER, 
	"HR_CS" NUMBER, 
	"HR_SAC" NUMBER, 
	"HR_SF" NUMBER, 
	"HR_BB" NUMBER, 
	"HR_IBB" NUMBER, 
	"HR_HBP" NUMBER, 
	"HR_SO" NUMBER, 
	"HR_GDP" NUMBER, 
	"HR_SLG" NUMBER, 
	"HR_OBP" NUMBER, 
	"HR_E" NUMBER, 
	"HR_SBP" NUMBER, 
	"HR_MH" NUMBER, 
	"HR_OPS" NUMBER, 
	"HR_RISP" NUMBER, 
	"HR_PHBA" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_CODE" IS '타자성적코드';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."PL_CODE" IS '선수코드';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_YEAR" IS '연도';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_AVG" IS '타율';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_G" IS '경기';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_PA" IS '타석';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_AB" IS '타수';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_R" IS '득점';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_H" IS '안타';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_2B" IS '2루타';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_3B" IS '3루타';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_HR" IS '홈런';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_TB" IS '루타';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_RBI" IS '타점';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."BR_SB" IS '도루';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_CS" IS '도루실패';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_SAC" IS '희생번트';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_SF" IS '희생플라이';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_BB" IS '볼넷';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_IBB" IS '고의4구';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_HBP" IS '사구';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_SO" IS '삼진';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_GDP" IS '병살';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_SLG" IS '장타';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_OBP" IS '출루율';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_E" IS '실책';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_SBP" IS '도루성공율';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_MH" IS '멀티히트';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_OPS" IS '출루율+장타율';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_RISP" IS '득점권타율';
   COMMENT ON COLUMN "TOM"."HIT_RECORDS"."HR_PHBA" IS '대타타율';
   COMMENT ON TABLE "TOM"."HIT_RECORDS"  IS '타자성적';
--------------------------------------------------------
--  DDL for Table P_POSITION
--------------------------------------------------------

  CREATE TABLE "TOM"."P_POSITION" 
   (	"PP_CODE" NUMBER, 
	"PP_NAME" NVARCHAR2(10)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "TOM"."P_POSITION"."PP_CODE" IS '선수포지션코드';
   COMMENT ON COLUMN "TOM"."P_POSITION"."PP_NAME" IS '포지션명';
   COMMENT ON TABLE "TOM"."P_POSITION"  IS '선수포지션';
--------------------------------------------------------
--  DDL for Table P_PT
--------------------------------------------------------

  CREATE TABLE "TOM"."P_PT" 
   (	"PT_CODE" NUMBER, 
	"PT_NAME" NVARCHAR2(4)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "TOM"."P_PT"."PT_CODE" IS '투타코드';
   COMMENT ON COLUMN "TOM"."P_PT"."PT_NAME" IS '투타구분명';
   COMMENT ON TABLE "TOM"."P_PT"  IS '투타정보';
--------------------------------------------------------
--  DDL for Table P_STATE
--------------------------------------------------------

  CREATE TABLE "TOM"."P_STATE" 
   (	"PS_CODE" NUMBER, 
	"PS_STATE" NVARCHAR2(10)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "TOM"."P_STATE"."PS_CODE" IS '선수상태코드';
   COMMENT ON COLUMN "TOM"."P_STATE"."PS_STATE" IS '상태이름';
   COMMENT ON TABLE "TOM"."P_STATE"  IS '선수상태';
--------------------------------------------------------
--  DDL for Table PITCH_RECORDS
--------------------------------------------------------

  CREATE TABLE "TOM"."PITCH_RECORDS" 
   (	"PR_CODE" NUMBER, 
	"PL_CODE" NUMBER, 
	"PR_YEAR" NUMBER, 
	"PR_ERA" NUMBER, 
	"PR_G" NUMBER, 
	"PR_CG" NUMBER, 
	"PR_SHO" NUMBER, 
	"PR_W" NUMBER, 
	"PR_L" NUMBER, 
	"PR_SV" NUMBER, 
	"PR_HLD" NUMBER, 
	"PR_WPCT" NUMBER, 
	"PR_TBF" NUMBER, 
	"PR_NP" NUMBER, 
	"PR_IP" NUMBER, 
	"PR_H" NUMBER, 
	"PR_2B" NUMBER, 
	"PR_3B" NUMBER, 
	"PR_HR" NUMBER, 
	"PR_SAC" NUMBER, 
	"PR_SF" NUMBER, 
	"PR_BB" NUMBER, 
	"PR_IBB" NUMBER, 
	"PR_SO" NUMBER, 
	"PR_WP" NUMBER, 
	"PR_BK" NUMBER, 
	"PR_R" NUMBER, 
	"PR_ER" NUMBER, 
	"PR_BSV" NUMBER, 
	"PR_WHIP" NUMBER, 
	"PR_AVG" NUMBER, 
	"PR_QS" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_CODE" IS '투수성적코드';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PL_CODE" IS '선수코드';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_YEAR" IS '연도';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_ERA" IS '평균자책점';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_G" IS '경기';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_CG" IS '완투';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_SHO" IS '완봉';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_W" IS '승';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_L" IS '패';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_SV" IS '세이브';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_HLD" IS '홀드';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_WPCT" IS '승률';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_TBF" IS '타자수';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_NP" IS '투구수';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_IP" IS '이닝';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_H" IS '피안타';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_2B" IS '2루타';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_3B" IS '3루타';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_HR" IS '피홈런';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_SAC" IS '희생번트';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_SF" IS '희생플라이';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_BB" IS '볼넷';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_IBB" IS '고의4구';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_SO" IS '탈삼진';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_WP" IS '폭투';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_BK" IS '보크';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_R" IS '실점';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_ER" IS '자책점';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_BSV" IS '블론세이브';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_WHIP" IS '이닝당출루허용률';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_AVG" IS '피안타율';
   COMMENT ON COLUMN "TOM"."PITCH_RECORDS"."PR_QS" IS '퀄리티스타트';
   COMMENT ON TABLE "TOM"."PITCH_RECORDS"  IS '투수성적';
--------------------------------------------------------
--  DDL for Table PLAYER
--------------------------------------------------------

  CREATE TABLE "TOM"."PLAYER" 
   (	"PL_CODE" NUMBER, 
	"T_CODE" NUMBER, 
	"PP_CODE" NUMBER, 
	"PT_CODE" NUMBER, 
	"PS_CODE" NUMBER, 
	"PL_NAME" NVARCHAR2(20), 
	"PL_BIRTH" DATE, 
	"PL_HEIGHT" NUMBER, 
	"PL_WEIGHT" NUMBER, 
	"PL_BN" NUMBER, 
	"PL_ES" NVARCHAR2(50), 
	"PL_MS" NVARCHAR2(50), 
	"PL_HS" NVARCHAR2(50), 
	"PL_UNIV" NVARCHAR2(50), 
	"PL_FOR" NVARCHAR2(20), 
	"PL_CAREER" NVARCHAR2(100), 
	"PL_JYEAR" NUMBER, 
	"PL_NRANK" NVARCHAR2(100), 
	"PL_AS" NUMBER, 
	"PL_PIC" NVARCHAR2(200)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "TOM"."PLAYER"."PL_CODE" IS '선수코드';
   COMMENT ON COLUMN "TOM"."PLAYER"."T_CODE" IS '구단코드';
   COMMENT ON COLUMN "TOM"."PLAYER"."PP_CODE" IS '선수포지션코드';
   COMMENT ON COLUMN "TOM"."PLAYER"."PT_CODE" IS '투타코드';
   COMMENT ON COLUMN "TOM"."PLAYER"."PS_CODE" IS '선수상태코드';
   COMMENT ON COLUMN "TOM"."PLAYER"."PL_NAME" IS '이름';
   COMMENT ON COLUMN "TOM"."PLAYER"."PL_BIRTH" IS '생년월일';
   COMMENT ON COLUMN "TOM"."PLAYER"."PL_HEIGHT" IS '신장';
   COMMENT ON COLUMN "TOM"."PLAYER"."PL_WEIGHT" IS '체중';
   COMMENT ON COLUMN "TOM"."PLAYER"."PL_BN" IS '등번호';
   COMMENT ON COLUMN "TOM"."PLAYER"."PL_ES" IS '출신초';
   COMMENT ON COLUMN "TOM"."PLAYER"."PL_MS" IS '출신중';
   COMMENT ON COLUMN "TOM"."PLAYER"."PL_HS" IS '출신고';
   COMMENT ON COLUMN "TOM"."PLAYER"."PL_UNIV" IS '출신대';
   COMMENT ON COLUMN "TOM"."PLAYER"."PL_FOR" IS '군팀';
   COMMENT ON COLUMN "TOM"."PLAYER"."PL_CAREER" IS '경력';
   COMMENT ON COLUMN "TOM"."PLAYER"."PL_JYEAR" IS '입단년도';
   COMMENT ON COLUMN "TOM"."PLAYER"."PL_NRANK" IS '지명순위';
   COMMENT ON COLUMN "TOM"."PLAYER"."PL_AS" IS '연봉';
   COMMENT ON COLUMN "TOM"."PLAYER"."PL_PIC" IS '선수사진';
   COMMENT ON TABLE "TOM"."PLAYER"  IS '선수';
--------------------------------------------------------
--  DDL for Table SP_KIND
--------------------------------------------------------

  CREATE TABLE "TOM"."SP_KIND" 
   (	"SK_CODE" NUMBER, 
	"SK_NAME" NVARCHAR2(10)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "TOM"."SP_KIND"."SK_CODE" IS '협찬분야코드';
   COMMENT ON COLUMN "TOM"."SP_KIND"."SK_NAME" IS '분야명';
   COMMENT ON TABLE "TOM"."SP_KIND"  IS '스폰서협찬분야';
--------------------------------------------------------
--  DDL for Table SPONSER
--------------------------------------------------------

  CREATE TABLE "TOM"."SPONSER" 
   (	"SP_CODE" NUMBER, 
	"T_CODE" NUMBER, 
	"SK_CODE" NUMBER, 
	"SP_NAME" NVARCHAR2(10), 
	"SP_AMOUNT" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "TOM"."SPONSER"."SP_CODE" IS '스폰서코드';
   COMMENT ON COLUMN "TOM"."SPONSER"."T_CODE" IS '구단코드';
   COMMENT ON COLUMN "TOM"."SPONSER"."SK_CODE" IS '협찬분야코드';
   COMMENT ON COLUMN "TOM"."SPONSER"."SP_NAME" IS '기업명';
   COMMENT ON COLUMN "TOM"."SPONSER"."SP_AMOUNT" IS '금액';
   COMMENT ON TABLE "TOM"."SPONSER"  IS '구단스폰서';
--------------------------------------------------------
--  DDL for Table ST_FACILITY
--------------------------------------------------------

  CREATE TABLE "TOM"."ST_FACILITY" 
   (	"SF_CODE" NUMBER, 
	"FC_CODE" NUMBER, 
	"SF_NAME" NVARCHAR2(20), 
	"SF_PIC" NVARCHAR2(200), 
	"SF_EX" NVARCHAR2(500), 
	"SF_CHARGE" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "TOM"."ST_FACILITY"."SF_CODE" IS '시설코드';
   COMMENT ON COLUMN "TOM"."ST_FACILITY"."FC_CODE" IS '시설분류코드';
   COMMENT ON COLUMN "TOM"."ST_FACILITY"."SF_NAME" IS '시설이름';
   COMMENT ON COLUMN "TOM"."ST_FACILITY"."SF_PIC" IS '시설사진';
   COMMENT ON COLUMN "TOM"."ST_FACILITY"."SF_EX" IS '시설설명';
   COMMENT ON COLUMN "TOM"."ST_FACILITY"."SF_CHARGE" IS '시설이용료';
   COMMENT ON TABLE "TOM"."ST_FACILITY"  IS '구장시설';
--------------------------------------------------------
--  DDL for Table STADIUM
--------------------------------------------------------

  CREATE TABLE "TOM"."STADIUM" 
   (	"ST_CODE" NUMBER, 
	"T_CODE" NUMBER, 
	"ST_NAME" NVARCHAR2(10), 
	"ST_ADDRESS" NVARCHAR2(100), 
	"ST_PH" NVARCHAR2(20), 
	"ST_FAX" NVARCHAR2(20), 
	"ST_SPIC" NVARCHAR2(200), 
	"ST_SEATS" NUMBER, 
	"ST_AREA" NUMBER, 
	"SF_CODE" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "TOM"."STADIUM"."ST_CODE" IS '구장코드';
   COMMENT ON COLUMN "TOM"."STADIUM"."T_CODE" IS '구단코드';
   COMMENT ON COLUMN "TOM"."STADIUM"."ST_NAME" IS '구장명';
   COMMENT ON COLUMN "TOM"."STADIUM"."ST_ADDRESS" IS '주소';
   COMMENT ON COLUMN "TOM"."STADIUM"."ST_PH" IS '전화번호';
   COMMENT ON COLUMN "TOM"."STADIUM"."ST_FAX" IS '팩스';
   COMMENT ON COLUMN "TOM"."STADIUM"."ST_SPIC" IS '좌석배치도';
   COMMENT ON COLUMN "TOM"."STADIUM"."ST_SEATS" IS '좌석수';
   COMMENT ON COLUMN "TOM"."STADIUM"."ST_AREA" IS '면적';
   COMMENT ON COLUMN "TOM"."STADIUM"."SF_CODE" IS '시설코드';
   COMMENT ON TABLE "TOM"."STADIUM"  IS '구장';
--------------------------------------------------------
--  DDL for Table TEAM
--------------------------------------------------------

  CREATE TABLE "TOM"."TEAM" 
   (	"T_CODE" NUMBER, 
	"T_NAME" NVARCHAR2(10), 
	"T_HTOWN" NVARCHAR2(10), 
	"T_OWNER" NVARCHAR2(10), 
	"T_FYEAR" NUMBER, 
	"T_EMBLEM" NVARCHAR2(200), 
	"T_LOGO" NVARCHAR2(200), 
	"T_SYMBOL" NVARCHAR2(200), 
	"T_MASCOT" NVARCHAR2(200)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "TOM"."TEAM"."T_CODE" IS '구단코드';
   COMMENT ON COLUMN "TOM"."TEAM"."T_NAME" IS '구단명';
   COMMENT ON COLUMN "TOM"."TEAM"."T_HTOWN" IS '연고지';
   COMMENT ON COLUMN "TOM"."TEAM"."T_OWNER" IS '구단주';
   COMMENT ON COLUMN "TOM"."TEAM"."T_FYEAR" IS '창단년도';
   COMMENT ON COLUMN "TOM"."TEAM"."T_EMBLEM" IS '엠블럼';
   COMMENT ON COLUMN "TOM"."TEAM"."T_LOGO" IS '구단로고';
   COMMENT ON COLUMN "TOM"."TEAM"."T_SYMBOL" IS '구단상징';
   COMMENT ON COLUMN "TOM"."TEAM"."T_MASCOT" IS '구단마스코트';
   COMMENT ON TABLE "TOM"."TEAM"  IS '구단';
--------------------------------------------------------
--  DDL for Table TEAM_RECORDS
--------------------------------------------------------

  CREATE TABLE "TOM"."TEAM_RECORDS" 
   (	"TR_CODE" NUMBER, 
	"T_CODE" NUMBER, 
	"TR_YEAR" NUMBER, 
	"TR_G" NUMBER, 
	"TR_W" NUMBER, 
	"TR_D" NUMBER, 
	"TR_L" NUMBER, 
	"TR_WPCT" NUMBER, 
	"TR_RANK" NUMBER, 
	"TR_RA" NUMBER, 
	"TR_RL" NUMBER, 
	"TR_HR" NUMBER, 
	"TR_SB" NUMBER, 
	"TR_AVG" NUMBER, 
	"TR_ERA" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "TOM"."TEAM_RECORDS"."TR_CODE" IS '팀성적코드';
   COMMENT ON COLUMN "TOM"."TEAM_RECORDS"."T_CODE" IS '구단코드';
   COMMENT ON COLUMN "TOM"."TEAM_RECORDS"."TR_YEAR" IS '연도';
   COMMENT ON COLUMN "TOM"."TEAM_RECORDS"."TR_G" IS '경기';
   COMMENT ON COLUMN "TOM"."TEAM_RECORDS"."TR_W" IS '승';
   COMMENT ON COLUMN "TOM"."TEAM_RECORDS"."TR_D" IS '무';
   COMMENT ON COLUMN "TOM"."TEAM_RECORDS"."TR_L" IS '패';
   COMMENT ON COLUMN "TOM"."TEAM_RECORDS"."TR_WPCT" IS '승률';
   COMMENT ON COLUMN "TOM"."TEAM_RECORDS"."TR_RANK" IS '순위';
   COMMENT ON COLUMN "TOM"."TEAM_RECORDS"."TR_RA" IS '득점';
   COMMENT ON COLUMN "TOM"."TEAM_RECORDS"."TR_RL" IS '실점';
   COMMENT ON COLUMN "TOM"."TEAM_RECORDS"."TR_HR" IS '홈런';
   COMMENT ON COLUMN "TOM"."TEAM_RECORDS"."TR_SB" IS '도루';
   COMMENT ON COLUMN "TOM"."TEAM_RECORDS"."TR_AVG" IS '타율';
   COMMENT ON COLUMN "TOM"."TEAM_RECORDS"."TR_ERA" IS '방어율';
   COMMENT ON TABLE "TOM"."TEAM_RECORDS"  IS '팀성적';
