--------------------------------------------------------
--  파일이 생성됨 - 월요일-3월-23-2020   
--------------------------------------------------------
@D:\★\ex-im\TABLES.sql
--@D:\★\ex-im\C_DETAIL_DATA_TABLE.xlsx
--@D:\★\ex-im\C_POSITION_DATA_TABLE.xlsx
--@D:\★\ex-im\COACHING_STAFF_DATA_TABLE.xlsx
--@D:\★\ex-im\FC_KIND_DATA_TABLE.xlsx
--@D:\★\ex-im\HIT_RECORDS_DATA_TABLE.xlsx
--@D:\★\ex-im\P_POSITION_DATA_TABLE.xlsx
--@D:\★\ex-im\P_PT_DATA_TABLE.xlsx
--@D:\★\ex-im\P_STATE_DATA_TABLE.xlsx
--@D:\★\ex-im\PITCH_RECORDS_DATA_TABLE.xlsx
--@D:\★\ex-im\PLAYER_DATA_TABLE.xlsx
--@D:\★\ex-im\SP_KIND_DATA_TABLE.xlsx
--@D:\★\ex-im\SPONSER_DATA_TABLE.xlsx
--@D:\★\ex-im\ST_FACILITY_DATA_TABLE.xlsx
--@D:\★\ex-im\STADIUM_DATA_TABLE.xlsx
--@D:\★\ex-im\TEAM_DATA_TABLE.xlsx
--@D:\★\ex-im\TEAM_RECORDS_DATA_TABLE.xlsx
@D:\★\ex-im\INDEXES.sql
@D:\★\ex-im\CONSTRAINTS.sql
